spring.application.name=rest-api

# Timeouts del cliente HTTP
http.client.connect-timeout=5000
http.client.read-timeout=5000

jsonplaceholder.base-url=https://jsonplaceholder.typicode.com

# Endpoints
jsonplaceholder.posts=/posts
jsonplaceholder.postByPost=/posts/{postId}
jsonplaceholder.commentsByPostId=/posts/{postId}/comments
jsonplaceholder.usersByUserId=/users/{userId}

